### ISSUE TITLE
Test file missing for SamPay.php file

### ISSUE THREAD

**Issue by blessedjasonmwanza** [blessedjasonmwanza/Payments-MiddleWare#2]
Hi @kazashim , kindly create some test/ usage file showing examples of use cases of the SamPay API.

**Comment by kazashim** [comment]
Yeah sure Working on it!

**Comment by blessedjasonmwanza** [comment]
> Yeah sure Working on it!

Kindly advise on the date of possible implication of the requested test file .

Thanks && Happy Hacking/ >

**Comment by blessedjasonmwanza** [comment]
Hi @kazashim , How far with the test file?

**Comment by blessedjasonmwanza** [comment]
Hello @kazashim 
> Provided that this issue remains unattended during the course of the next 7 days, **your code/commit patch will be removed** to maintain the project clarity for usage. 

Thanks && HappyHacking/>
