### ISSUE TITLE
Create a demo sandbox for this API

### ISSUE THREAD

**Issue by Mwansasquared** [blessedjasonmwanza/Payments-MiddleWare#3]

**Comment by blessedjasonmwanza** [comment]
>Hello  @Mwansasquared , Thanks for raising this issue up. Will do so within the next few days.

__#HappyCoding__

**Comment by blessedjasonmwanza** [comment]
Hello again @Mwansasquared , Post interaction with the payment gateway, it seems like Sparco do not provide sandbox testing endpoints.

> **Workaround Suggestion:** [Visit Sparco Gateway website](https://gateway.sparco.io/register)  and Signup for an account to obtain your private and Public Key required for integration. As per **PaymentsMiddleWare* current doc.

>I am working on deploying other options for a variant of choice selection, depending on your needs. 

#HappyCoding/>
